name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIG: 'Release'
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration $BUILD_CONFIG
      - name: Transfer Assets
        run: cp Assets/x64/libargon2.so Source/Argon2.Interop.Tests/bin/Release/net7.0/
      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration $BUILD_CONFIG
      - name: Pack
        run: dotnet pack --configuration $BUILD_CONFIG
      - name: Publish
        run: |
          dotnet nuget add source --username Flash619 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Flash619/index.json"
          dotnet nuget push **\*.nupkg --source "github"